# Copyright 2022 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: gcr.io/span-cloud-testing/jmeter-slave:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1099
            - containerPort: 50000
          volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-key
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
      volumes:
      - name: google-cloud-key
        secret:
          secretName: sa-key