# Copyright 2024 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

FROM gcr.io/cloud-spanner-emulator/machmeter-jmeter-base:latest
EXPOSE 60000
