CREATE TABLE user (
    userId STRING(160) NOT NULL,
    apiKey STRING(128) NOT NULL,
    partnerId STRING(128) NOT NULL,
    createdAtInSecs INT64 NOT NULL,
    updatedAtInSecs INT64 NOT NULL,
    deviceInfo JSON,
    eulaAcceptedState BOOL,
    eulaAcceptedStateUpdatedAtInSecs INT64,
    enabledState BOOL,
    subscriptions JSON,
    preferredNetworkType STRING(32),
    extras JSON,
    preferredCategories ARRAY<STRING(64)>,
    version INT64,
    disableActionType STRING(256),
    enableReferrer STRING(256),
    adPersonalizationEnabled BOOL,
    firstEnableReferrer STRING(256),
    clientVersion STRING(32),
    subscribedCategories JSON,
    staticSegments ARRAY<INT64>,
    showRecommendations BOOL,
    firstEnableAtInSecs INT64,
    categoryOptOut BOOL,
    languageSubscriptions JSON,
    nickname STRING(256),
    sdkVersion INT64,
    state INT64,
    city INT64,
    region STRING(16),
    locale STRING(32),
    dynamicSegments ARRAY<STRING(48)>,
    userEngagement JSON,
    dataSaverEnabled BOOL,
    ownedAppPackageNames ARRAY<STRING(128)>,
    resetCacheAtInSecs INT64,
    highlightsDetails JSON,
    userStated JSON,
    sdkFeatures JSON,
    isChildLockEnabled BOOL,
    childLockTimeLimit INT64,
    monthAndYearOfBirth STRING(16),
    locationInfo JSON,
    optOutOfSale BOOL,
    systemFlags JSON,
    systemFlagsUpdatedAtInSecs INT64
) PRIMARY KEY(userId);

CREATE TABLE user_bal (
    userId STRING(128) NOT NULL,
    cSpent INT64,
    cEarn INT64,
    cEarnToday INT64,
    balance FLOAT64 NOT NULL,
    engmtLvl STRING(30),
    streakDay STRING(30),
    source STRING(60),
    cEarnUpdatedAt INT64,
    engmtLvlUpdatedAt INT64,
    streakDayUpdatedAt INT64,
    creationTime TIMESTAMP,
    updationTime TIMESTAMP,
    currStreakFirstEarnAt INT64,
    sourceTransactLog JSON,
) PRIMARY KEY(userId);


CREATE TABLE user_txns (
    userId STRING(128) NOT NULL,
    transactionId STRING(128) NOT NULL,
    org_transId STRING(128),
    amount FLOAT64 NOT NULL,
    balance FLOAT64,
    currency STRING(50),
    streakDay STRING(30),
    transactionType STRING(50),
    transactionStatus STRING(50),
    RewardType STRING(50),
    refType STRING(50),
    refTypeId STRING(128),
    transactionSource STRING(60),
    creationTime TIMESTAMP,
) PRIMARY KEY(userId, transactionId),
 INTERLEAVE IN PARENT user_bal ON DELETE CASCADE;

CREATE INDEX user_txnsByTransactionId ON user_txns(transactionId);